"""
Deterministic Feedback adapter for local development and tests.

Intent:
    Allow end-to-end flows without invoking the real DSPy/Ollama stack.
    The adapter emits stable Markdown feedback and a criteria report.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable

from backend.learning.adapters.ports import FeedbackResult


class StubFeedbackAdapter:
    """Generate predictable feedback content for development."""

    def analyze(self, *, text_md: str, criteria: Iterable[str]) -> FeedbackResult:
        criteria_list = list(criteria) or ["overall"]
        criteria_results = [
            {
                "criterion": criterion,
                "score": 8,
                "explanation_md": f"- Stub evaluation for **{criterion}** based on provided text.",
            }
            for criterion in criteria_list
        ]
        # Emit criteria.v2: add max_score for clarity and keep overall score on 0..5 scale.
        v2_results = [
            {**item, "max_score": 10} for item in criteria_results
        ]
        return FeedbackResult(
            feedback_md="### Stub feedback\n\n- Great effort! (Generated by stub adapter.)",
            analysis_json={
                "schema": "criteria.v2",
                "score": 4,
                "criteria_results": v2_results,
            },
        )


def build() -> StubFeedbackAdapter:
    """Factory used by the worker to instantiate the adapter."""
    return StubFeedbackAdapter()
