-- Refactor mastery learning tables for the new algorithm and store answers.

-- Step 1: Drop the old table if it exists.
-- We also drop the submission table to ensure a clean slate on reruns.
DROP TABLE IF EXISTS public.mastery_submission;
DROP TABLE IF EXISTS public.student_mastery_progress;

-- Step 2: Create the new student_mastery_progress table with the new schema.
CREATE TABLE public.student_mastery_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    task_id UUID REFERENCES public.task(id) ON DELETE CASCADE NOT NULL,
    
    -- Core Algorithm Fields
    stability FLOAT DEFAULT 1.0 NOT NULL,          -- Memory stability in days
    difficulty FLOAT DEFAULT 0.5 NOT NULL,         -- Intrinsic difficulty (0.0 to 1.0)
    
    -- Tracking Fields
    last_reviewed_at TIMESTAMPTZ,
    next_due_date DATE NOT NULL,
    
    CONSTRAINT student_mastery_progress_student_id_task_id_key UNIQUE (student_id, task_id)
);

-- Add comments to the new table and columns
COMMENT ON TABLE public.student_mastery_progress IS 'Stores student progress on mastery tasks based on the new spaced repetition algorithm.';
COMMENT ON COLUMN public.student_mastery_progress.stability IS 'S: The strength of the memory in days.';
COMMENT ON COLUMN public.student_mastery_progress.difficulty IS 'D: The intrinsic difficulty of the task (0.0 = easy, 1.0 = hard).';
COMMENT ON COLUMN public.student_mastery_progress.last_reviewed_at IS 'Timestamp of the last completed review.';
COMMENT ON COLUMN public.student_mastery_progress.next_due_date IS 'The date when the task is scheduled for the next review.';

-- Step 3: Create the mastery_submission table to store answers.
CREATE TABLE public.mastery_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    task_id UUID REFERENCES public.task(id) ON DELETE CASCADE NOT NULL,
    
    -- The student's answer
    answer_text TEXT NOT NULL,
    
    -- AI Assessment Results (q_vec)
    korrektheit FLOAT NOT NULL,
    vollstaendigkeit FLOAT NOT NULL,
    praegnanz FLOAT NOT NULL,
    reasoning TEXT
);

-- Add comments to the submission table
COMMENT ON TABLE public.mastery_submission IS 'Stores student answers and AI assessments for mastery tasks.';
COMMENT ON COLUMN public.mastery_submission.answer_text IS 'The verbatim answer provided by the student.';
COMMENT ON COLUMN public.mastery_submission.korrektheit IS 'AI assessment: Correctness score (0.0 to 1.0).';
COMMENT ON COLUMN public.mastery_submission.vollstaendigkeit IS 'AI assessment: Completeness score (0.0 to 1.0).';
COMMENT ON COLUMN public.mastery_submission.praegnanz IS 'AI assessment: Conciseness/Clarity score (0.0 to 1.0).';
COMMENT ON COLUMN public.mastery_submission.reasoning IS 'The textual reasoning for the AI assessment.';


-- Step 4: Enable Row Level Security (RLS)
ALTER TABLE public.student_mastery_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mastery_submission ENABLE ROW LEVEL SECURITY;

-- Step 5: Create RLS Policies
-- Students can only see and manage their own progress and submissions.
CREATE POLICY "Allow student to access their own mastery progress" 
    ON public.student_mastery_progress
    FOR ALL
    USING (auth.uid() = student_id)
    WITH CHECK (auth.uid() = student_id);

CREATE POLICY "Allow student to access their own mastery submissions" 
    ON public.mastery_submission
    FOR ALL
    USING (auth.uid() = student_id)
    WITH CHECK (auth.uid() = student_id);

-- Teachers should be able to see their students' progress. This requires a function.
-- We will add this policy later if required, for now, only students can access their data.
